server:
  port: 8085 #端口
spring:
  profiles:
    active: dev #项目环境
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${demo.datasource.driver-class-name}
      url: jdbc:mysql://${demo.datasource.host}:${demo.datasource.port}/${demo.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${demo.datasource.username}
      password: ${demo.datasource.password}
  redis:
    host: ${demo.redis.host}
    port: ${demo.redis.port}
    password:
    lettuce:
      pool:
        max-active: ${demo.redis.lettuce.pool.max-active}
        max-idle: ${demo.redis.lettuce.pool.max-idle}
        min-idle: ${demo.redis.lettuce.pool.min-idle}
        time-between-eviction-runs: ${demo.redis.lettuce.pool.time-between-eviction-runs}
mybatis-plus:
  type-aliases-package: com.bfw.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted #逻辑删除 1删除 0未删除
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #mybatis日志记录
demo:
  jwt:
    admin-secret-key: admin
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: user
    user-ttl: 7200000
    user-token-name: authentication