server:
  port: 8085 #端口
spring:
  profiles:
    active: dev #项目环境
  datasource:
    druid:
      driver-class-name: ${demo.datasource.driver-class-name}
      url: jdbc:mysql://${demo.datasource.host}:${demo.datasource.port}/${demo.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${demo.datasource.username}
      password: ${demo.datasource.password}
mybatis-plus:
  type-aliases-package: com.bfw.entity
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #mybatis日志记录